### ISSUE TITLE
USB Backup - Does not create "Your QuikBackup" folder on user`s flash drive.

### ISSUE THREAD

**Issue by djdarien** [djdarien/Quik-Backup#2] opened 2015-09-22 16:40 UTC
copies original file folder name and its contents.   

SUCCESS SHOULD BE:    USB BACKUP - "Your QuikBackup" created.

**Comment by djdarien** [comment] 2015-09-23 18:12
Tested today on my flash drive and it was a success.... leaving this issue open

**Comment by pugking9** [comment] 2015-09-24 12:22
Known issue. No longer seems to be a problem, thought to be caused by leftover proccess created from bad application closing. Fixed by handling Close() event.

**Closed as completed by pugking9** 2015-09-24 12:22 UTC
